FROM python:latest
RUN apt-get update
RUN apt-get -y upgrade
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install flask_cors
RUN pip install jsonify
RUN pip install secure-smtplib
RUN pip install mariadb
WORKDIR /flaskProject
CMD ["python", "app.py"]
