version: "3.4"
services:
  webserver:
    build:
      context: ./flaskServer
    ports:
      - "80:5000"
    links:
      - mariadb
    restart: 'always'
    volumes:
      - ./flaskServer/webserver:/flaskProject
  mariadb:
    image: mariadb:10.6-focal
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minervatech
      MYSQL_USER: minervatech
      MYSQL_PASSWORD: MinervallTech
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'Phpmyadmin'
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '800:80'

